#!/usr/bin/env bash
# transfer file to web server

# enter right syntax
if [ $# -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# assign variablea
file=$1
ip=$2
user=$3
key=$4

# add file to server
scp -o StrickHostKeyChecking=no -i $key $file $user@$ip:~/
