#!/usr/bin/env bash
# task 1

# Update package lists
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Ensure Nginx is listening on port 80
sudo ufw allow 'Nginx HTTP'

# Create a custom index.html with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Restart Nginx to apply changes
sudo service nginx restart
