#!/usr/bin/env bash
# Configuring Nginx server

# Update package lists
sudo apt-get update -y

# Install Nginx
sudo apt-get install nginx -y

# Ensure Nginx is listening on port 80
sudo ufw allow 'Nginx HTTP'

# Create a custom index.html with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Add a permanent redirection to /redirect_me
sed -i "s/server_name _;/server_name _;\n\trewrite \/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
