#!/usr/bin/env bash
# install load balancer and configure to send traffic to 2 servers

sudo apt-get update -y
sudo apt-get install haproxy -y

# Backup the original HAProxy config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

# Configure HAProxy
cat << EOF | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 434763-web-01 52.3.250.188:80 check
    server 434763-web-02 52.23.212.81:80 check

EOF

# Enable HAProxy service to start on boot
sudo update-rc.d haproxy enable

# Restart HAProxy to apply the new configuration
sudo service haproxy restart
