#!/usr/bin/env bash
# install load balancer and configure to send traffic to 2 servers

sudo apt-get update -y
sudo apt-get install haproxy

# Backup the original HAProxy config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

# Configure HAProxy
sudo cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 434763-web-01 52.3.250.188:80 check
    server 434763-web-01 52.23.212.81:80 check

EOF

# Enable HAProxy service to start on boot
update-rc.d haproxy enable

# Restart HAProxy to apply the new configuration
sudo service haproxy restart
