#!/usr/bin/env bash
# configure nginx to run as nginx user

sudo chown -R nginx:nginx /etc/nginx
sudo sed -i "s|80 default_server;|8080 default_server;|" /etc/nginx/sites-available/default
sudo service nginx restart
